#pragma once

#include <alpaqa/util/problem.hpp>

#include <string>

namespace alpaqa {

/// @addtogroup grp_ExternalProblemLoaders
/// @{

/// @todo Specialize
using CasADiProblem = LambdaProblem;
/// @todo Specialize
using CasADiProblemWithParam = LambdaProblemWithParam;

/// Load a problem generated by CasADi (without parameters).
///
/// @param  filename
///         Filename of the shared library to load the functions from.
/// @param  n
///         Number of decision variables (@f$ x \in \mathbb{R}^n @f$).
/// @param  m
///         Number of general constraints (@f$ g(x) \in \mathbb{R}^m @f$).
/// @param  second_order
///         Load the additional functions required for second-order PANOC.
///
/// The file should contain functions with the names `f`, `grad_f`, `g` and
/// `grad_g`. These functions evaluate the objective function, its gradient,
/// the constraints, and the constraint gradient times a vector respecitvely.
/// If @p second_order is true, additional functions `hess_L` and
/// `hess_L_prod` should be provided to evaluate the Hessian of the Lagrangian
/// and Hessian-vector products.
///
/// If any of the dimensions are zero, they are determined from the `g` function
/// in the given file.
///
/// @throws std::invalid_argument
///         The dimensions of the loaded functions do not match.
CasADiProblem load_CasADi_problem(const std::string &filename, unsigned n = 0,
                                  unsigned m = 0, bool second_order = false);
/// Load a problem generated by CasADi (with parameters).
///
/// @param  filename
///         Filename of the shared library to load the functions from.
/// @param  n
///         Number of decision variables (@f$ x \in \mathbb{R}^n @f$).
/// @param  m
///         Number of general constraints (@f$ g(x) \in \mathbb{R}^m @f$).
/// @param  p
///         The number of parameters of the problem (second argument to all
///         CasADi functions).
/// @param  second_order
///         Load the additional functions required for second-order PANOC.
///
/// The file should contain functions with the names `f`, `grad_f`, `g` and
/// `grad_g`. These functions evaluate the objective function, its gradient,
/// the constraints, and the constraint gradient times a vector respecitvely.
/// If @p second_order is true, additional functions `hess_L` and
/// `hess_L_prod` should be provided to evaluate the Hessian of the Lagrangian
/// and Hessian-vector products.
///
/// If any of the dimensions are zero, they are determined from the `g` function
/// in the given file.
///
/// @throws std::invalid_argument
///         The dimensions of the loaded functions do not match.
CasADiProblemWithParam
load_CasADi_problem_with_param(const std::string &filename, unsigned n = 0,
                               unsigned m = 0, unsigned p = 0,
                               bool second_order = false);

/// @}

} // namespace alpaqa